server:
  port:8080
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: hh
        jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.0.235:5432/horus_heresy
    username: postgres
    password: 0nlineSt0r@geServer
    schema: hh

management:
  endpoints:
    web:
      exposure:
        exclude:
        include: *